In [1]:
import numpy as np

In [4]:
# basic data structure in numpy is an ndarray
arr = np.ndarray([2,2])# defines an array of 2*2 with random numbers

In [5]:
arr

array([[6.94996379e-310, 6.94996379e-310],
       [6.94996379e-310, 4.00193173e-322]])

In [6]:
np.shape(arr)

(2, 2)

In [7]:
# 3*3*2 => 3d array
d3_array = np.ndarray([3,2,2]) 

In [8]:
d3_array

array([[[6.94996077e-310, 6.94994942e-310],
        [6.94994942e-310, 6.94994942e-310]],

       [[6.94994942e-310, 6.94994942e-310],
        [7.11454530e-322, 3.95252517e-322]],

       [[0.00000000e+000, 3.16202013e-322],
        [0.00000000e+000, 6.94994942e-310]]])

In [9]:
# python like slicing works in array

In [11]:
arr = np.ndarray([9,])# one dimesional array

In [12]:
arr

array([6.94996083e-310, 6.94996083e-310, 6.94996083e-310, 6.94996083e-310,
       6.94996083e-310, 6.94996083e-310, 6.94996083e-310, 6.94996083e-310,
       6.94996083e-310])

In [25]:
arr2 = arr.reshape(-1,1,1) # reshape the array to x,1 where x is old dimension

In [26]:
np.shape(arr) # one dimensional array

(9,)

In [27]:
np.shape(arr2) # 2d array with one column

(9, 1, 1)

In [28]:
# numpy can only have one data type, differnet from python lists

In [50]:
l = [1, 'yuvraj',3.45]

In [51]:
arr = np.array(l)

In [52]:
arr # 1 is converted to `1` a unicode string

array(['1', 'yuvraj', '3.45'], dtype='<U21')

In [32]:
arr = np.array([1,2,3,4])

In [33]:
arr

array([1, 2, 3, 4])

In [37]:
arr.reshape()

array([[1, 2, 3, 4]])

In [38]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])

In [39]:
a

array([[1, 2],
       [3, 4]])

In [40]:
b

array([[4, 5],
       [6, 7]])

In [48]:
# numpy allows element wise operations

In [42]:
a + b

array([[ 5,  7],
       [ 9, 11]])

In [43]:
a - b

array([[-3, -3],
       [-3, -3]])

In [44]:
a * b

array([[ 4, 10],
       [18, 28]])

In [45]:
a / b

array([[0.25      , 0.4       ],
       [0.5       , 0.57142857]])

In [46]:
a // b

array([[0, 0],
       [0, 0]])

In [47]:
b // a

array([[4, 2],
       [2, 1]])

In [49]:
b ** a

array([[   4,   25],
       [ 216, 2401]])

In [53]:
d = b ** a

In [54]:
d.sum()

2646

In [59]:
d.sum(axis = 1)# axis lets you sum across dimensions

array([  29, 2617])

In [60]:
# you can do mean, etc. as well in the same manner
print(d.mean())
print(d.mean(axis=0))
print(d.mean(axis=1))


661.5
[ 110. 1213.]
[  14.5 1308.5]


In [62]:
d.flatten()

array([   4,   25,  216, 2401])

In [86]:
big_array = np.random.random([1,10000000])

In [87]:
def sum(big_array):
    total = 0
    for i in big_array:
        total = total + i
    return total

In [88]:
arr = np.array(big_array)

In [89]:
arr.sum()

5002127.875677194

In [90]:
import time

In [91]:
start = time.time()
sum(big_array)
end = time.time()
end - start

0.02134847640991211

In [92]:
start = time.time()
arr.sum()
end = time.time()
end - start

0.010370731353759766

In [75]:
0.5766189098358154/0.015835046768188477 # numpy is 36 times faster

36.41409578872879

In [93]:
# matrix multiplication
a.dot(b)

array([[16, 19],
       [36, 43]])

In [100]:
def matrix(X,Y):
    result = np.zeros([len(X), len(Y)])
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]
    return result

In [101]:
matrix(a,b)

array([[16., 19.],
       [36., 43.]])

In [108]:
m1 = np.random.random([1000,1000])

In [109]:
m2 = np.random.random([1000,1000])

In [110]:
start = time.time()
matrix(m1, m2)
end = time.time()
end - start

KeyboardInterrupt: 

In [111]:
start = time.time()
m1.dot(m2)
end = time.time()
end - start

0.10462594032287598

In [106]:
1.4704914093017578/0.07624983787536621


19.285174241358284

In [107]:
# numpy is very very fast for mathematical calculations